### PR TITLE
Migrate to original gl-matrix package

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/toji/gl-matrix/commits?author=TrySound

I spent some time to achieve esm support in original gl-matrix package.
Now you may cherry pick modules like this

```js
import * as vec2 from 'gl-matrix/vec2';
import { transformMat4 } from 'gl-matrix/vec3';
```

Cherry picking every function is not relevant since modules are
relatively small and treeshakable (all functions are pure).

This eliminates the necessity in commonjs transformations of transitive
dependencies with rollup.

### CODE REVIEW

**Comment by TrySound** [comment]
@ibgreen @Pessimistress any comments on this guys?

**Comment by TrySound** [comment]
@ibgreen @Pessimistress Friendly ping :)

**Comment by Pessimistress** [comment]
Does webpack support tree shaking when using `import * as`? It's not clear from the documentation. I'll run some tests today.

If we merge this, we'll need to publish it as 3.0-alpha.

**Comment by TrySound** [comment]
Well, webpack itself has really small abilities in treeshaking. Mostly it's terser work. But yes, simple functions can be treeshaked just fine.

Why major? There are not breaking changes here. I didn't see any changes in splitted packages. All tests are passed.

**Comment by Pessimistress** [comment]
> Why major?

I'll need to do a thorough audit here, but some dependents of this package reference the implicit dependencies, e.g. https://github.com/uber-common/viewport-mercator-project/blob/master/src/web-mercator-viewport.js

**Comment by Pessimistress** [comment]
@TrySound I did an audit of the dependents. Both deck.gl and viewport-mercator-project are importing gl-* packages. At this point if we publish this change as a minor release, applications that lock down to an existing deck.gl version will be broken.

My suggested course of action:
- We publish 3.0.0-alpha now, and you can force resolve all math.gl dependencies to the new version.
- We update deck.gl and viewport-mercator-project to use `gl-matrix`
- The next deck.gl release will depend on math.gl v3.0

**Pull request merged**
